environment:
  matrix:
    - GENERATOR_NAME: "Visual Studio 14 2015"
    - GENERATOR_NAME: "Visual Studio 14 2015 Win64"

    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      GENERATOR_NAME: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      GENERATOR_NAME: "Visual Studio 15 2017 Win64"

platform: x64
configuration: Release

install:
- git submodule update --init --recursive

build_script:

- mkdir build
- cd build
- cmake -G "%GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=Release ..
- cmake --build . --config "Release"
- ctest
