name: Build linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    # if: false  # This workflow is disabled
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make build-essential 

    - name: Build static pksav
      run: |
        mkdir build_static
        cd build_static
        cmake .. -DPKSAV_STATIC=ON -DPKSAV_ENABLE_TESTS=OFF -DPKSAV_ENABLE_DOCS=OFF
        make 

    - name: Build dynamic pksav
      run: |
        mkdir build_dynamic
        cd build_dynamic
        cmake .. -DPKSAV_STATIC=OFF -DPKSAV_ENABLE_TESTS=OFF -DPKSAV_ENABLE_DOCS=OFF
        make
    
    - name: Bundle library
      run: |
        mkdir -p build/release/include
        cp -r build_static/lib/libpksav.a build/release
        cp -r build_dynamic/lib/libpksav.so build/release
        cp -r build_static/include/* build/release/include

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pksav-linux-amd64
        path: build/release
