name: Build and Bundle Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    # if: false  # This workflow is disabled
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make build-essential libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libgl1-mesa-dev

    - name: Build pksav
      run: |
        cd deps/pksav/
        mkdir build
        cd build
        cmake .. -DPKSAV_STATIC=ON
        make 

    - name: Build raylib
      run: |
        cd deps/raylib/src/
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install

    - name: Build Project
      run: |
        make

    - name: Bundle Assets
      run: |
        # Copy assets to the same directory as the executable
        mkdir -p build/assets
        cp -r assets/* build/assets/

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pokeromtrader-artifacts-linux
        path: build/
