name: Build and Bundle Windows

on:
  push:
    branches:
      - main

jobs:
  build_x64:
    if: false  # This workflow is disabled
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup MSVC Environment (x64)
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        architecture: x64

    - name: Build pksav
      run: |
        cd deps/pksav/
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: Build raylib
      run: |
        cd deps/raylib/src/
        mingw32-make PLATFORM=PLATFORM_DESKTOP

    - name: Build Project
      run: |
        mingw32-make PLATFORM=PLATFORM_DESKTOP

    - name: Bundle Executable with Library
      run: |
        # Copy libpksav.dll to the same directory as the executable
        cp deps/pksav/build/Release/libpksav.dll build/
      
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pokeromtrader-artifacts  # Specify a name for your artifacts
        path: build/  # Specify the directory containing your build artifacts
