name: Build and Test

on:
  push:
    branches:
      - v2/main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64]  # Specify the desired architectures here

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build libpksav
      run: |
        cd libpksav/
        cmake .
        make 

    - name: Build Project
      run: |
        make all

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pokeromtrader.out  # Specify a name for your artifacts
        path: src/  # Specify the directory containing your build artifacts

    - name: Clean Up
      run: |
        make clean
