name: Build and Bundle Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_windows:
    # if: false  # This workflow is disabled
    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3
      
    - name: Setup msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64

    - name: Build pksav
      run: |
        cd deps/pksav/
        mkdir build
        cd build
        cmake .. -DPKSAV_STATIC=ON -G "Unix Makefiles" -DPKSAV_ENABLE_TESTS=OFF -DPKSAV_ENABLE_DOCS=OFF -DPKSAV_ENABLE_APPS=OFF -DPKSAV_ENABLE_LIBRARY=OFF -DCMAKE_BUILD_TYPE=Release
        make

    - name: Build raylib
      run: |
        cd deps/raylib/src/
        make PLATFORM=PLATFORM_DESKTOP

    - name: Build Project
      run: |
        make

    - name: Copy assets
      run: |
        mkdir -p build/assets
        cp assets/icon.ico build/assets/icon.ico
        cp assets/pkrom.rc.data build/assets/pkrom.rc.data
      
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pokeromtrader-artifacts-windows
        path: build/
