name: Build and Bundle Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_windows:
    # if: false  # This workflow is disabled
    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3
      
    - name: Setup msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64

    - name: Build pksav
      run: |
        cd deps/pksav/
        mkdir build
        cd build
        cmake .. -DPKSAV_STATIC=ON -G "Unix Makefiles"
        make

    - name: Build raylib
      run: |
        cd deps/raylib/src/
        make PLATFORM=PLATFORM_DESKTOP

    - name: Build Project
      run: |
        make PLATFORM=PLATFORM_DESKTOP

    - name: Bundle Executable with Library
      run: |
        # Copy libpksav.a to the same directory as the executable
        cp deps/pksav/build/lib/libpksav.a build/

    - name: Copy assets
      run: |
        cp -r assets build
      
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pokeromtrader-artifacts-windows  # Specify a name for your artifacts
        path: build/  # Specify the directory containing your build artifacts
